apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
  annotations:
    # --- IMAGE UPDATER CONFIG ---
    argocd-image-updater.argoproj.io/node-app.image: ghcr.io/jenishcloudengineer/gitops-node-app
    argocd-image-updater.argoproj.io/node-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/JenishCloudEngineer/GitOps-Style-with-argocd.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
